export const String = {
  app: {
    App: 'Schedulic Staff',
    datanotfound: 'No data found',
    Nointernet: 'No Internet Connection!',
  },
  login: {
    AppoitmentBookingApp: 'Appointment Booking Application',
    LoginText: 'Login',
    SignText: ' Sign Up',
    ContinueButton: ' Continue ',
  },
  loginmain: {
    loginAccount: 'Login To Your Account',
    loginDeatils: 'Enter your details to login.',
    loginplaceholderEmail: 'Enter your email id',
    loginplaceholderPassword: 'Enter password',
    Rememberme: 'Remember Me',
    LoginButtom: 'Login',
    error_message_allFieldsManatory: 'All Fields Are Mandatory',
    error_message_email: 'Please Enter Email',
    error_message_email_valid: 'Please Enter Valid Email-id',
    error_message_password: 'Please Enter Password',
    error_message_password_length: 'Please Enter 8 Digit Password',
    error_message_phone_no: 'Please Enter Phone number',
    error_message_phone_length: 'Please Enter 10 Digit mobile number',
    error_message_fname: 'Please Enter Firstname',
    error_message_lname: 'Please Enter Lastname',
  },
  home: {
    Helloword: 'Hello!',
    Newbooking: 'New Bookings',
    Describtion: 'Lorem ipsum dolor',
    Ongoing: 'Ongoing',
    TaskCompleted: 'Task Completed',
    home: 'Home',
  },
  invoice: {
    Sendinvoice: 'Send Invoice',
    Businessname: 'Xyz Salon',
    invoicename: 'INVOICE',
    Billname: 'Bill To',
    invoicenumber: 'Invoice No.',
    invoicedate: 'Invoice Date',
    Description: 'Description',
    Amount: 'Amount',
    Unit: 'Unit',
    LineTotal: 'LineTotal',
    SubTotal: 'Sub Total',
    Discount: 'Discount',
  },
  payment: {
    cash: 'cash',
    Online: 'Online',
    Instore: 'Instore',
    Next: 'Next',
    paymants: 'Paymant',
    paymantDetails: 'Payment Details',
  },
  account: {
    MyAccount: 'My Account',
    category: 'Category',
    postlCode: 'Postal Codes',
    workinghr: 'Working Hours',
    breaks: ' Breaks',
    timeoff: 'Time Off',
    shareApp: 'Share App',
    rateus: 'Rate Us',
    logout: 'Logout',
    mobileNumber: 'Phone number',
    update: 'Update',
    accountDetails: 'Account Details',
    name: 'Enter name',
    fname: 'Enter Firstname',
    lname: 'Enter Lastname',
    logoutMessage: 'Are you sure you want to logout?',
    to: 'to',
    notification: 'Notification',
  },
  MyBookingTab: {
    myBooking: 'My Booking',
    detail: 'Details',
    date_time: 'Date & Time',
    satus: 'Status',
    servicest: 'Services',
    details: 'Details',
    pay: 'Pay',
    amount: 'Amount',
    customer: 'Customer',
    customer_detail: 'Customer Details',
    note: 'Note :',
    tracknow: 'Track Now',
    servicetype: 'Service Type',
    accept: 'Accept',
    reject: 'Reject',
    reschedule: 'Reschedule',
    ontheway: 'On The Way',
    workstarted: 'Work Started',
    map: 'Map',
    completed: 'Completed',
    invoice: 'Invoice',
    rating: 'Rating',
    staff: 'Staff',
    services: 'Service :',
    select_date: 'Select Date',
    select_time: 'Select Time',
    addnote: 'Add Note',
    next: 'Next',
    confirm: 'confirm',
    error_message_select_startdate: 'Please select start date',
  },

  cashpaymant: {
    amount: 'Amount',
    service: 'Service',
    coupon: 'Coupon',
    couponcode: 'Coupon Code',
    total: 'Total',
    coupon_code_applied: 'Coupone Applied',
    paid: 'Paid',
    paymantlink: 'Send Paymant link to customer',
    cancel: 'Cancel',
  },
  success: {
    paymantdone: 'Paymant Done Successfully',
    bookDes:
      'Paymant Completed. An Email.with Details of \n Your booking and invoice has been send to you.',
    orderid: 'Order Id :',
    done: 'Done',
  },
  map: {
    map: 'Map',
    distance: 'Distance :',
    customer: 'Customer :',
  },
};
