export const SET_USER_DATA_BY_ID = 'SET_USER_DATA_BY_ID';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGOUT = 'LOGOUT';
export const SET_SETTING = 'GET_SETTING';
export const SET_SERVICE_LIST = 'SET_SERVICE_LIST';
export const TAX = 'TAX';
export const SEARCH_KEY = 'SEARCH_KEY';
export const SET_BUSINESS ='SET_BUSINESS'
