import {StyleSheet} from 'react-native';
import {Matrics, Color} from '../../utlis';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.white,
  },

  serviewText: {
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: Color.darkGray,
    margin: hp('2%'),
  },

  courseImgView: {
    backgroundColor: Color.white,
    borderRadius: 50 / 2,
    zIndex: 0,
    width:wp('10%')
  },
  courseImg: {
    width: Matrics.Scale(50),
    height: Matrics.Scale(50),
    borderRadius: 50 / 2,
    resizeMode: 'cover',
    backgroundColor: Color.white,
  },
  topView: {
    backgroundColor: Color.white,
    justifyContent: 'center',
    alignSelf: 'center',
    width: wp('90%'),
    borderRadius: Matrics.Scale(10),
    // borderWidth:1,
    elevation: 1,
    shadowOpacity: 0.5,
    shadowRadius: 1,
    shadowOffset: {width: 0, height: 2},
    padding:hp('1%')
  },
  imgView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  userNameSyl: {
    width: wp('50%'),
    marginLeft: wp('10%'),
    color: Color.gray,
  },
  userAmount: {
    marginLeft: wp('3%'),
    color: Color.gray,
    
  },
  date: {
    color: Color.ligthGray,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  time: {
    color: Color.ligthGray,
    marginLeft: wp('2%'),
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  dateTimeView: {
    flexDirection: 'row',
    marginLeft: wp('3%'),
  },
  qtyView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    width: wp('25%'),
  },
  inc_dec_icon: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    color: Color.AppColor,
    padding: Matrics.Scale(10),
    fontSize: Matrics.Scale(16),
    fontWeight: '900',
  },
  textQty: {
    color: Color.AppColor,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  amountView: {
    flex:1,
    marginTop:hp('2%'),
    flexDirection: 'row',
    justifyContent:'center',
    alignSelf:'center',
  },
  amountAlertView: {
    marginTop:hp('1%'),
    justifyContent:'center',
    width: wp('90%'),
    fontSize: Matrics.Scale(16),
    fontWeight: '500',
    padding: Matrics.Scale(5),
    marginHorizontal: 20,
    color: 'red'
  },
  text_amount: {
    flex:1,
    color: Color.bleck,
    marginLeft: Matrics.Scale(20),
    fontSize: Matrics.Scale(16),
    fontWeight: '600',
    alignSelf: 'center'

  },
  text_rs: {
    flex: 1,
    color: Color.bleck,
    marginRight: Matrics.Scale(20),
    fontSize: Matrics.Scale(16),
    fontWeight: '600',
    alignSelf: 'center',
  },
  text_coupon: {
    flex: 1,
    color: Color.bleck,
    marginLeft: Matrics.Scale(20),
    fontSize: Matrics.Scale(16),
    fontWeight: '600',
    alignSelf: 'center',
  },
  text_coupon_applied: {
    color: Color.AppColor,
    width: wp('45%'),
    fontSize: Matrics.Scale(16),
    fontWeight: '600',
  },
  couponView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: Color.white,
    borderWidth: 1,
    borderColor: 'rgba(187, 187, 187, 1)',
    borderRadius: Matrics.Scale(5),
    marginRight: Matrics.Scale(20),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
  },
  couponViewApp: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: Color.white,
    width: wp('60%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
  },
  textCouponCode: {
    justifyContent: 'center',
    alignSelf: 'center',
    color: Color.bleck,
    fontSize: Matrics.Scale(16),
    width: wp('35%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
    paddingLeft:10
  },
  couponIconView: {
    backgroundColor: Color.AppColor,
    borderWidth: 1,
    borderColor: Color.AppColor,
    borderTopEndRadius: Matrics.Scale(5),
    borderBottomEndRadius: Matrics.Scale(5),
  },
  inc_coupon: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    color: Color.white,
    padding: Matrics.Scale(10),
    fontSize: Matrics.Scale(16),
    fontWeight: 'bold',
  },
  borderView: {
    borderWidth: 1,
    borderColor: Color.ligthGray,
    borderRadius: Matrics.Scale(5),
    borderStyle: 'dashed',
    width: wp('90%'),
    margin: wp('4%'),
  },
  totalamountView: {
    flexDirection: 'row',
    backgroundColor: Color.ligthGray,
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
    alignSelf: 'center',
  },
  textTotal: {
    justifyContent: 'center',
    alignSelf: 'center',
    fontSize: Matrics.Scale(16),
    width: wp('50%'),
    marginLeft: wp('2%'),
    fontWeight: '900',
  },
  textTotalRs: {
    flex: 3,
    alignSelf: 'center',
    textAlign: 'right',
    fontSize: Matrics.Scale(16),
    marginRight: wp('2%'),
    fontWeight: '900',
  },
  add_more_serviceMainView: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: wp('90%'),
    marginTop: hp('25%'),
  },
  buttonStylpass: {

  backgroundColor:Color.AppColor,
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
  },
  buttonTextView: {
    justifyContent: 'center',
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    textAlign: 'center',
  },
  textChange: {
    color: Color.white,
    fontWeight: '500',
    fontSize: Matrics.Scale(16),
    width: wp('90%'),
    textAlign: 'center',
  },
  proceedtocheckMainView: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: wp('90%'),
    marginTop: hp('1.5%'),
    marginBottom: hp('2%'),
  },
  buttonStylupdate: {
    borderWidth: 1,
    borderColor: 'rgba(66, 77, 228, 1)',
    borderRadius: Matrics.Scale(5),
    backgroundColor: Color.white,
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('6%'),
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    textAlign: 'center',
  },
  textUpdate: {
    color: Color.AppColor,
    fontWeight: '500',
    fontSize: Matrics.Scale(16),
    textAlign: 'center',
  },
  currencySymbolView:{
    flex: 1,
    flexDirection: 'row', 
    padding: 10,
    marginRight: wp('5%'),
    marginLeft: wp('3%'),
    borderWidth: 1,
    borderRadius: Matrics.Scale(5),
    borderColor: 'rgba(187, 187, 187, 1)',
  },
  currencySymbolAmount:{
    flex: .1,
    textAlign: 'right', 
    paddingTop: 5,
    paddingBottom: 5,
    paddingTop: 5,
    paddingRight: 2,
    fontSize: Matrics.Scale(16),
    fontWeight: '600',
    backgroundColor: 'white'
  }
});
