import {Platform, StyleSheet} from 'react-native';
import {Matrics, Color} from '../../../utlis';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.white,
  },
  mainView: {
    height: hp('100%'),
  },
  inputView: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    width: wp('80%'),
  },
  inputBorde: {
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderWidth: 1,
    borderColor: 'rgba(187, 187, 187, 1)',
    borderRadius: Matrics.Scale(5),
    marginTop: Matrics.Scale(20),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('8%'),
  },
  inputBordePass: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderWidth: 1,
    borderColor: 'rgba(187, 187, 187, 1)',
    borderRadius: Matrics.Scale(5),
    marginTop: Matrics.Scale(20),
    width: wp('80%'),
  },
  textCode: {
    justifyContent: 'center',
    color: Color.bleck,
    fontSize: Matrics.Scale(18),
    width: wp('70%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('8%'),
    marginLeft: wp('2%'),
  },
  verticalView: {
    backgroundColor: Color.ligthGray,
    width: 1,
    height: hp('4%'),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textMobileNumber: {
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    color: Color.bleck,
    fontSize: Matrics.Scale(18),
    fontWeight: '400',
    fontStyle: 'normal',
    marginLeft: Matrics.Scale(20),
  },
  containerPhone: {
    height: Matrics.Scale(30),
    alignItems: 'center',
    justifyContent: 'center',
    padding: Matrics.Scale(10),
    alignSelf: 'center',
  },

  inputViewStyl: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderWidth: 1,
    borderColor: 'rgba(187, 187, 187, 1)',
    borderRadius: Matrics.Scale(5),
    marginTop: Matrics.Scale(20),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('8%'),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  changeButtonMainView: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: wp('90%'),
    marginTop: hp('40%'),
  },
  buttonStylpass: {
    borderWidth: 1,
    borderColor: 'rgba(66, 77, 228, 1)',
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('8%'),
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    textAlign: 'center',
  },

  loginButtonMainView: {
    justifyContent: 'center',
    alignSelf: 'center',
    width: wp('90%'),
   
  },
  textChange: {
    justifyContent: 'center',
    color: Color.AppColor,
    fontWeight: '500',
    fontSize: Matrics.Scale(18),
    textAlign: 'center',
    top: Platform.OS === 'ios' ? hp('1%') : hp('2%'),
  },
  buttonStylupdate: {
   
    backgroundColor: 'rgba(66, 77, 228, 1)',
    borderRadius: Matrics.Scale(5),
    width: wp('90%'),
    height: Platform.OS == 'ios' ? hp('6%') : hp('8%'),
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    textAlign: 'center',
  },
  textUpdate: {
    justifyContent: 'center',
    color: Color.white,
    fontWeight: '500',
    fontSize: Matrics.Scale(18),
    textAlign: 'center',
    top: Platform.OS === 'ios' ? hp('1%') : hp('2%'),
  },
  pickerStyle: {
    height: Platform.OS == 'ios' ? hp('5%') : hp('7%'),
    width: Matrics.Scale(105),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    padding: 10,
    marginLeft: 10,
    // borderWidth: 0,
    // borderColor: '#303030',
    backgroundColor: 'white',
  },
  selectedCountryTextStyle: {
    paddingLeft: 5,
    paddingRight: 5,
    color: '#000',
    textAlign: 'right',
  },
  containerCode: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
});
